
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_TYPE = 32;
  public static final int STRING_LITERAL = 28;
  public static final int BOOL_TYPE = 31;
  public static final int MULT = 9;
  public static final int RSQ_BRACK = 14;
  public static final int CHAR = 29;
  public static final int L_CBRACK = 21;
  public static final int INTEGER = 2;
  public static final int LPAREN = 11;
  public static final int BADCHAR = 19;
  public static final int MINUS = 8;
  public static final int RAT_TYPE = 34;
  public static final int RPAREN = 12;
  public static final int PERIOD_SYM = 15;
  public static final int INF = 24;
  public static final int COMMA = 23;
  public static final int SEMICOL = 6;
  public static final int DIV = 10;
  public static final int PLUS = 7;
  public static final int MAIN = 20;
  public static final int EOF = 0;
  public static final int EQUAL = 5;
  public static final int TRUE = 38;
  public static final int DICTIONARY = 36;
  public static final int error = 1;
  public static final int LSQ_BRACK = 13;
  public static final int INT_TYPE = 33;
  public static final int R_CBRACK = 22;
  public static final int TOP = 26;
  public static final int DEUX_POINTS = 17;
  public static final int LET = 4;
  public static final int SUP = 25;
  public static final int UNDERSCORE = 16;
  public static final int LEN = 18;
  public static final int STRING = 30;
  public static final int SEQUENCE = 37;
  public static final int FALSE = 39;
  public static final int FLOAT_TYPE = 35;
  public static final int PRINT = 27;
  public static final int IDENTIFIER = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "IDENTIFIER",
  "LET",
  "EQUAL",
  "SEMICOL",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "LPAREN",
  "RPAREN",
  "LSQ_BRACK",
  "RSQ_BRACK",
  "PERIOD_SYM",
  "UNDERSCORE",
  "DEUX_POINTS",
  "LEN",
  "BADCHAR",
  "MAIN",
  "L_CBRACK",
  "R_CBRACK",
  "COMMA",
  "INF",
  "SUP",
  "TOP",
  "PRINT",
  "STRING_LITERAL",
  "CHAR",
  "STRING",
  "BOOL_TYPE",
  "CHAR_TYPE",
  "INT_TYPE",
  "RAT_TYPE",
  "FLOAT_TYPE",
  "DICTIONARY",
  "SEQUENCE",
  "TRUE",
  "FALSE"
  };
}

